# RNN minor project - SENTIMENT ANALYSIS

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("IMDB Dataset.csv")

In [3]:
df.shape

(50000, 2)

In [4]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [6]:
df.drop_duplicates(inplace = True)

In [7]:
df.shape

(49582, 2)

## Pre-processing

Text processing 
1) convert to lowercase
2) remove the url(http)
3) remove the html
4) remove the puntuations
5) remove the stopwords
6) stemming - convert word to the rootform of the word
7) encode sentiments
8) vectorization

### 1) converting to lowercase

In [8]:
df["review"] = df["review"].str.lower()

### 2) remove the url

In [9]:
# using the library of a python to do so re(regular expression)
#library - re
# sub function - used for substitute
import re

#e.g->
#sample_text = "abc is the word" # abc => xyz
#new_text = re.sub("abc" , "xyz" , sample_text)

In [10]:
def remove_url(text):
    text = re.sub( r"http\S+" , "" , text)
    # (pattern , replace , strin)
    return text
df["review"] = df["review"].apply(remove_url)   
# \S vs \s 
# \s - included white space 
#\S - not included the white space

### 3). removing the punctuations

In [11]:
def remove_punctuations(text):
    text = re.sub( r"^[A-Za-z0-9\s]" , "" , text) 
    return text 

df["review"] = df["review"].apply(remove_punctuations)

### 4)removing HTML tags

In [12]:
### 4)removing HTML tags 
def remove_html(text):
    text = re.sub( r"<.*?>" , "" , text) 
    return text 

df["review"] = df["review"].apply(remove_html)

### 5) Removing the Stopwords

In [4]:
# we gonna use the nlkt library
# firstly we have to toeknized the whole sentence 

import nltk 
nltk.download("punkt")# sentence tokenizer 
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\abcfo\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\abcfo\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\abcfo\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [13]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [24]:
#sample_text = "I like coding in python !"
#tokens = word_tokenize(sample_text)

In [14]:
# function to remove the stop words

def remove_stopwords(text):
    tokens = word_tokenize(text) # tokeized the words 
    stop_words = stopwords.words("english") #stopwords of all the english 


    for word in tokens:
        if word in stop_words:
            text = text.replace(word , "")

    return text 

df["review"] = df["review"].apply(remove_stopwords)

In [16]:
df.head()

                                              review sentiment
0  ne    revewers  nted   wtchg  1 oz epode 'll  ...  positive
1   wderful ltle producti.  filming technique   u...  positive
2   thought    wderful wy  spend tme   o hot summ...  positive
3  sclly 's  fmly   lttle boy (jke) thks 's  zomb...  negative
4  etter mttei's "love   time  mey"   vully stunn...  positive

## 6. stemming

In [17]:
# running - run
# played - play
# this by using porterstemming algorithm

from nltk.stem import PorterStemmer

In [26]:
def stemming(text):
    ps = PorterStemmer()
    stemmed_words = []

    tokens = word_tokenize(text)
    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)

    return " ".join(stemmed_words)

df["review"]= df["review"].apply(stemming)

## 7) encoding for the target value

In [33]:
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()
df["sentiment"] = le.fit_transform(df["sentiment"])

In [36]:
y = df["sentiment"]

In [37]:
y # the postive = 1 , and the negative = 0

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

## 8 ) vectorization

In [ ]:
# the data into the numbers 
# inbuilt module 
# converts the raw documents to a matrux of the TF-id

In [51]:
# the mattrix gonna be this big because of the large data so will we use the max_featuer parameter to limit the vocabulary , means olny using the most feateurs onlu 

from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(max_features= 5000)

X = tf.fit_transform(df["review"])

In [52]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4058804 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 2769)	0.0452089458772002
  (0, 3543)	0.05270869359214474
  (0, 2882)	0.08759996960918758
  (0, 4942)	0.10746309757648152
  (0, 3014)	0.5423241521799081
  (0, 1288)	0.12756246810103422
  (0, 2294)	0.09253086457135733
  (0, 1934)	0.07564231033053144
  (0, 3557)	0.09209686639243589
  (0, 1376)	0.059600026597106885
  (0, 1967)	0.05882519464685032
  (0, 1628)	0.07210058390934483
  (0, 4365)	0.039687496870858395
  (0, 4168)	0.17143930199262752
  (0, 3699)	0.03219841622164607
  (0, 4743)	0.256052582374392
  (0, 3811)	0.04250543398956109
  (0, 4775)	0.11104870717201076
  (0, 1747)	0.03548959652575682
  (0, 4494)	0.073270290998456
  (0, 3861)	0.16861791283453717
  (0, 1638)	0.05850192134867197
  (0, 1865)	0.06966049104298999
  (0, 3339)	0.06135091106519965
  (0, 3343)	0.08005542932702255
  :	:
  (49581, 2880)	0.06172977606765278
  (49581, 1548)	0.10687061000910539
  (49581, 2818)	0.09159850310691066
  (49581, 4491)	0.05751411500916528
  (49581, 4990)	0.08944241625474998
  (49581, 4927)	0.2213728504887049
  (49581, 4958)	0.09699574457549422
  (49581, 1673)	0.0894744629881915
  (49581, 443)	0.06832058009238609
  (49581, 4271)	0.06701039610717457
  (49581, 2224)	0.05831026503373056
  (49581, 4341)	0.10645788459532064
  (49581, 3652)	0.05220035355293682
  (49581, 1980)	0.07808362420502651
  (49581, 533)	0.07505609115460082
  (49581, 3117)	0.09973468283662089
  (49581, 2731)	0.817633866180394
  (49581, 1881)	0.08257494677402125
  (49581, 4457)	0.09762436172366361
  (49581, 346)	0.08937851500449462
  (49581, 2706)	0.1061816478926071
  (49581, 449)	0.08087720870132187
  (49581, 1286)	0.08435793583060991
  (49581, 3497)	0.09238710296157207
  (49581, 2861)	0.10048366177682781

In [53]:
# now we cam feed this to the RNN

## Dataset and DataLoader

In [57]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train , y_test = train_test_split(
    X , y , test_size = 0.2 , random_state = 42
)

In [59]:
X_train.shape

(39665, 5000)

In [60]:
X_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 809135 stored elements and shape (9917, 5000)>

In [65]:
import torch

from torch.utils.data import TensorDataset , DataLoader

In [66]:
#the above data is in the sparse matrix 
# firstly we have to convert it into the array 
X_train = X_train.toarray()
X_test = X_test.toarray()

AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

In [67]:
train_set = TensorDataset(
    torch.from_numpy(X_train).float(),
    torch.from_numpy(y_train.values).float()
)

test_set = TensorDataset(
    torch.from_numpy(X_test).float(),
    torch.from_numpy(y_test.values).float()
)

In [69]:
train_loader = DataLoader(train_set , shuffle = True , batch_size = 64)
test_loader = DataLoader(test_set , shuffle = True , batch_size = 64)

# build RNN

In [71]:
import torch.nn as nn
import torch.optim as optimizer

In [ ]:
class RNN(nn.Module):
    def __init__(self , input_size , hidden_size = 128 , num_layer = 1):
        super().__init__()


        self.hidden_size = hidden_size
        self.num_layer = num_layer


        # RNN layer
        self.rnn = nn.RNN(input_size , hidden_size , num_layer , batch_first = True)

        # fully connected layer
        self.fc = nn.Linear(hidden_size, )
        # many to one architecture 

    def forward(self , x):
        #optional -> sahpe(num of layer , batch_size , hidden size)
        h0 =